### PR TITLE
feat: data - add ellen to about page

### PR DESCRIPTION
**Pull request by paulstey**
This PR adds Ellen to the `About` page, and includes a main and hover photo. 

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [x] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ ] Commitizen was used for all commits.
- [ ] Local site looks as expected after changes.
- [ ] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Review by mirestrepo — APPROVED** [review]
💚

**Review by mcmcgrath13 — CHANGES_REQUESTED** [review]
Ellen should be between Camilo and I (alphabetical by first name)

**Comment by paulstey** [comment]
> Ellen should be between Camilo and I (alphabetical by first name)

Fixed! Thanks, @mcmcgrath13!!

**Review by mcmcgrath13 — APPROVED** [review]

**Comment by paulstey** [comment]
Thank you, @mcmcgrath13 and @mirestrepo!!!

**Pull request merged**
