### PR TITLE
Rdata

### PR DESCRIPTION
**Pull request by singhsaluja**
### Pull Request
---

#### PR Summary
Briefly describe the changes.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [x] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Review by paulstey — APPROVED** [review]
This looks great! Thank you, @singhsaluja!!

**Review by mirestrepo — CHANGES_REQUESTED** [review]
This is great, but what I had suggested and others agreed on is that we take the storage information out of this website an put it on the knowledge base, where all the other storage information lives.

See https://ithelp.brown.edu/agent/go/ticket/194557 for links to relate Knowledge Base articles.

I think in this website we should get rid of the cards for RData and Campus File Storage in this link https://ccv.brown.edu/services/#file-storage-and-transfer which should basically only link to this storage guide https://ccv.brown.edu/services/infrastructure/storage/ (the one being read from Knowledge Base via RSS). Eventually, BrownBox should also be deprecated. We should possibly also get rod of the Globus card since it's already mentioned in the storage Guide

**Review by singhsaluja — COMMENTED** [review]
@mirestrepo can we approve this to be merged? We'll take care of the kb article via deskpro ticket. There are other requests dependent on this. Thanks.

**Comment by singhsaluja** [comment]
The R-data section will be deleted.

**Pull request closed without merging**
