### PR TITLE
Feat: Edits to People Section

### LINKED ISSUE #407: [DATA] | Add Robert Gemma to people
**What would you like to update**
- [ ] people

I would prefer to have the `Gemma_Funny` photo be my secondary photo but I totally understand if you don't want that many URI logos in my pictures. If so, the `Gemma_Funny_2` photo works great too! 😄 

```yml
- name: Robert Gemma, Jr.
  weight: "11"
  type: Full Time
  team: Advanced Research Computing
  subteam: Data & Visualization
  title: Research Software Engineer
  github_username: RobertGemmaJr
  brown_directory_uuid: e78668ed-0e7a-4e5f-a69e-ab4a5015961c
  bio: ""
  image: robert_main.jpg
```
Gemma_Main
Gemma_Funny
Gemma_Funny_2

### PR DESCRIPTION
**Pull request by eldu**
### Pull Request
---

#### PR Summary
- Add Hadley to interns
- Remove all other interns except Minsik.
- Remove Andras
- Add Rob
- Move Matt to GSDC

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [x] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ ] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Review by paulstey — CHANGES_REQUESTED** [review]
Thank you so much, @eldu!! If you don't mind, could we also please remove Andras and change Matt's affiliation to be `Data & Visualization`?

**Comment by mcmcgrath13** [comment]
Matt's `weight` also needs to be updated so he shows up after me in the data&viz section. Thanks!

image

**Review by RobertGemmaJr — APPROVED** [review]
Thanks or adding me! This will close issue #407 😄

**Review by mcmcgrath13 — APPROVED** [review]

**Review by paulstey — APPROVED** [review]
Thank you, @eldu!!

**Review by RobertGemmaJr — APPROVED** [review]

**Pull request merged**
