### PR TITLE
fix: 🐛 fix cards alignment

### PR DESCRIPTION
**Pull request by fernandogelin**
### Pull Request
---

#### PR Summary
Logic for card alignment was wrong.

#### Check the types of changes present in this PR:
- [x] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Review by paulstey — APPROVED** [review]
Thank you, @fernandogelin!!

**Review by mcmcgrath13 — CHANGES_REQUESTED** [review]
the spacing of the cards (l/r margins) is different than the software page

**Comment by paulstey** [comment]
Thanks for the fix, @fernandogelin!! I think it's all set now.

**Review by mcmcgrath13 — CHANGES_REQUESTED** [review]
should srotrage.json be there?

**Review by mcmcgrath13 — APPROVED** [review]

**Pull request merged**
