### PR TITLE
feat: 🎸 Updating Facilities Statement

### PR DESCRIPTION
**Pull request by AlexDuchnowski**
Updates statistics about computational resources and adds information
about dbGaP and Stronghold

### Pull Request
---

#### PR Summary
Briefly describe the changes.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [x] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [x] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Comment by paulstey** [comment]
This looks great!! Thank you, @AlexDuchnowski!!

**Review by paulstey — APPROVED** [review]

**Comment by yangliu2009** [comment]
Please merge the two paragraphs into one paragraph in the dbGap sections. Do the same for the Stronghold section. The new section names look great! Thanks.

**Comment by mcmcgrath13** [comment]
https://ccv-website-pr-360.herokuapp.com/services/infrastructure/oscar/ is out of date with the facilities statement - that should probably be updated too (or just linked out to somewhere else?)

**Review by yangliu2009 — APPROVED** [review]
Thanks, Alex.

**Pull request merged**
