### PR TITLE
Content rates

### PR DESCRIPTION
**Pull request by fernandogelin**
### Pull Request
---

#### PR Summary
This PR refers to changes made to the rates page by Singh. 
@singhsaluja I had to reopen because we changed the branching organization. Please review to make sure the content looks correct.
 

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [x] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [x] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Comment by mcmcgrath13** [comment]
@fernandogelin I can't get the website to `serve` using the instructions on the readme

Is there another step I need to run?
```
Error: Error building site: failed to render pages: render of "section" failed: "/Users/mmcgrat3/src/ccv-website/themes/gb-theme/layouts/workshops/list.html:52:30": execute of template failed: template: workshops/list.html:52:30: executing "content" at <sort $jsonData "type" "asc">: error calling sort: sequence must be provided
```

**Review by mcmcgrath13 — APPROVED** [review]

**Comment by paulstey** [comment]
@fernandogelin and @mcmcgrath13, 

Can we merge this? Are we still missing anything before making these corrections?

**Comment by mcmcgrath13** [comment]
@paulstey it needs a content reviewer to approve it before it can be merged - @singhsaluja is tagged, but you could also review it

**Comment by fernandogelin** [comment]
@paulstey if you're reviewing, these changes do it on the PR #167. That one has a deployment on PR and contains these changes.

**Comment by fernandogelin** [comment]
closing this, refer to PR #167

**Pull request closed without merging**
