### PR TITLE
Feature gcs

### PR DESCRIPTION
**Pull request by fernandogelin**
### Pull Request
---

#### PR Summary
This PR adds the new search functionality using Google Custom Search. The search is now only on the navbar and display results in a modal. 
GCS is set up to search the following websites:

- `ccv.brown.edu`
- `docs.ccv.brown.edu`
- `ccvstatus.brown.edu`
- `github.com/brown-ccv`
- `github.com/compbiocore`
- `medium.com/brown-ccv`
- `medium.com/compbiocore`

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [x] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Comment by fernandogelin** [comment]
this PR also removes the workshop section under classroom.

**Comment by mcmcgrath13** [comment]
If I search for some words I know exist on the website (`mission` `mary` `fernando`), no results come up, which seems wrong

**Review by mcmcgrath13 — APPROVED** [review]
How does google decide what is searchable?

**Comment by mcmcgrath13** [comment]
also, only my CBC github stuff is showing up, which feels wrong

**Pull request merged**
