### PR TITLE
Docs readme

### PR DESCRIPTION
**Pull request by fernandogelin**
### Pull Request
---

#### PR Summary
Updated README with new guidelines for Website contribution.
@hkershaw-brown, @mirestrepo, and @paulstey  Could you review the `README.md` file.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [x] :blowfish: Other. Specify: Documentation: README.md

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [x] If changes affect development, was the README updated?

### CODE REVIEW

**Review by mirestrepo — APPROVED** [review]
Content looks good to me

**Comment by mcmcgrath13** [comment]
It could be nice if the PR template include a section on if this closes/addresses any issues and if so, which?

**Comment by fernandogelin** [comment]
I guess I didn't follow my own rules of adding the issue to the commit message footer.. but that would do it.

**Comment by mcmcgrath13** [comment]
I consistently forget to do that because 1) when I'm committing, I'm not in gh-land so it's not readily available/top of mind 2) there's usually several commits related and not a single one to point to, so that dilutes my likelihood to mark it.  Given that I'm only human, would it be okay to add it to the PR template even though it's technically redundant with other guidelines?

**Review by paulstey — COMMENTED** [review]
The description of the `production` branch says that the _staging_ site can be found at `https://ccv.brown.edu`. Is that a typo?

**Comment by fernandogelin** [comment]
@paulstey where do you see that? I couldn't find it.

**Comment by fernandogelin** [comment]
@paulstey If you find it, can you make a comment on the code itself? Thanks!

**Pull request merged**
