### PR TITLE
Update documentation.yaml

### PR DESCRIPTION
**Pull request by kmilo9999**
added link to visualization software gitbook documentation

### Pull Request
---

#### PR Summary
Briefly describe the changes.
added link to visualization software gitbook documentation

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [x ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ ] Commitizen was used for all commits.
- [ ] Local site looks as expected after changes.
- [ ] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Review by mirestrepo — CHANGES_REQUESTED** [review]
The public link should be https://docs.ccv.brown.edu/visualization/ - the one you added is the editor private link.

However, If Stronghold, Oscar, Globus, don't need a link, then this shouldn't either.... I'm not sure where the logic is handled for the other ones

**Comment by mirestrepo** [comment]
@fernandogelin Where are the links for Oscar, Stronghold docs coming from? There are not listed in directly in https://github.com/brown-ccv/ccv-website/blob/master/data/documentation.yaml but they are somewhat composed somewhere else (but I can't fid it) @kmilo9999 I Imagine that the Item in the `documentation.yaml` needs to have the same name as the Gitbook. In this case `Visualization`

**Comment by kmilo9999** [comment]
I replaced the link to public url https://docs.ccv.brown.edu/visualization/

**Comment by mirestrepo** [comment]
If you don't include a link at all, and list the item as  ` name: Visualization` does it work? I think you don't need the URL

**Comment by mirestrepo** [comment]
Although, as it is is fine with me. I'll let @fernandogelin or @mcmcgrath13 chip in if that detail matters.

**Review by mirestrepo — APPROVED** [review]

**Comment by fernandogelin** [comment]
yep, @mirestrepo intuition is correct. If it is a Gitbook doc, we just need the name, but the name needs to match the doc name. The way @kmilo9999 set up should also work, and it's useful if you want to have a different name show up in the table of contents.

**Review by fernandogelin — APPROVED** [review]

**Comment by kmilo9999** [comment]
I still can change it, but "visualization" is too general for the purpose of that doc.

**Comment by mirestrepo** [comment]
I think it's goo as it is. I agree, Visualization seems to general

**Pull request merged**
