### PR TITLE
refactor: 💡 Revised wording on rates page

### PR DESCRIPTION
**Pull request by kubatarlowski**
Changed footnote to * and ** to distinguish from +. Fixed wording to
reflect Free exploratory accounts are available to everyone at Brown.
Revised description of priority accounts. Changed placemen of ++
footnote to accounts with large amounts of CPUs. Changed scratch purge
description to reflect policy better. Changed exploratory (PI sponsored)
to reflect that the cores/time is for all jobs. Added /year for condo
price. Fixed quota to 1TB

BREAKING CHANGE: none

Closes: 131

### Pull Request
---

#### PR Summary
Briefly describe the changes.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [x] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ ] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Comment by fernandogelin** [comment]
@kubatarlowski looks like this branch is outdated and it's missing some essential files. Please, merge `master` into your branch and resolve any conflict.

**Review by fernandogelin — CHANGES_REQUESTED** [review]
@kubatarlowski looks like this branch is outdated and it's missing some essential files. Please, merge `master` into your branch and resolve any conflicts.

**Comment by hkershaw-brown** [comment]
This commit is 25 files changed - it is way more that the change to the
rates page.

Helen Kershaw
Lead Research Software Engineer
Center for Computation and Visualization
Brown University
XSEDE Campus Champion
http://www.ccv.brown.edu

**Comment by fernandogelin** [comment]
@hkershaw-brown I only see one file changed. Can you just review the content for the rates page? I can check other things if needed.

**Comment by kubatarlowski** [comment]
Sorry bout that. I just pushed again. Is it fine now?

**Comment by hkershaw-brown** [comment]
The asterisks are better, but I don't think this is clear to users what the rates are. 

This is missing the memory info for the account types.   There is no cpu limits on the GPU accounts. 

The research data storage is not Isilon.   This is entirely unclear to users that they get 10TB per grant that they can use on Oscar or Isilion (or a combo).  It has no details about what users will be billed for based their existing Isilion use. 

'total per-job limit' doesn't make sense. 

High-performance Computing -> High-Performance Computing

Memory is not the same as storage.   

'all members affiliated with Brown.'  - this is a strange phrase

Can you buy condos?  Has CCV got rid of that option?

Group priority accounts don't exist anymore,  it probably is worth putting some text explaining to people that that group discount no longer exists. 

Do  you have description of the rates you can work off?  Maybe review that with Mete to see if it is complete and correct (and matches the slurm associations that are on Oscar), before editing the website.

**Comment by paulstey** [comment]
@fernandogelin & @mcmcgrath13 : I'm inclined to agree with Helen. I think there are a few things we can probably clean up and/or simplify for the users reading this.

@kubatarlowski : Would you mind sending me the link to the formal, in-house documentation we have? I can't seem to dig it up.

**Comment by kubatarlowski** [comment]
@paulstey I found this https://docs.ccv.brown.edu/oscar/ but it doesn't offer much information on account specifications/pricing. There might be drive documentation with more information but any docs like that haven't been shared with me.

**Comment by paulstey** [comment]
Thanks, @kubatarlowski!! 

I'm going to dig around and ask @mttunca to see where else we might have something. 

Oh, and we definitely will want to re-name and/or modify the description of "_Research Data Storage (Isilon)_" section. Unless I'm missing something, this part doesn't highlight that we are referring to data across Isilon, GPFS, and potentially other on-prem. Those TB numbers are referring to the data _across all our systems_, right? If so, we probably want to spend some time making this clear to the reader. Does this sound right, @mttunca? 

Oh, and I think we might consider veering away from the term "_Research Data_" in naming this section. That was a term of art that became "_RData_", which is GPFS. Haven't we had discussions regarding whether we want to continue using that name (i.e., "_RData_")?

**Comment by kubatarlowski** [comment]
@paulstey - I also found this https://ithelp.brown.edu/file.php/8692XACZSKPJPG8691206F4C523T/CCV-Service-Center-Rates-FY20-Overview-Sheet.pdf

**Comment by fernandogelin** [comment]
@paulstey @kubatarlowski @mttunca what's the status of this?

**Pull request closed without merging**
