### PR TITLE
fix: 🐛 change google search code

### LINKED ISSUE #220: [BUG] Search is showing ads
**Describe the bug**
I'm not sure if this has already been reported, but it seems our Google custom search is showing ads. Can this be turned off? 

If we can't turn off that functionality, I really think we ought to consider alternatives. 

As always, thank you!!

### PR DESCRIPTION
**Pull request by fernandogelin**
closes #220

### Pull Request
---

#### PR Summary
Change CSE search. New code doesn't have ads.

#### Check the types of changes present in this PR:
- [x] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Comment by mcmcgrath13** [comment]
@fernandogelin I still see ads on the test deployment

**Comment by mcmcgrath13** [comment]
also, the search bar has no visible delineation from the background on chrome 
image

**Comment by fernandogelin** [comment]
@mcmcgrath13 I don't see adds :/

**Comment by mcmcgrath13** [comment]
This is what I see when I search "paul stey"
image

**Comment by paulstey** [comment]
I'm not sure if you have made a change, @fernandogelin, but I'm not seeing ads on the Heroku deployment as of right now.

@mcmcgrath13: Do you still see ads?

**Comment by mcmcgrath13** [comment]
I no longer see ads, but the search bar itself still looks off

**Comment by fernandogelin** [comment]
chrome is annoying :/ the search bar looks small and weird but I haven't found a work around. It looks fine in Firefox and Safari. I would say let's merge and try to fix later.
What do you think? @paulstey @mcmcgrath13

**Comment by mcmcgrath13** [comment]
@fernandogelin I'm not seeing the heroku build - what causes heroku to choke occasionally?

**Comment by mcmcgrath13** [comment]
@fernandogelin the google search is usable now, so that works for me - @paulstey ?

**Review by mcmcgrath13 — APPROVED** [review]

**Review by paulstey — APPROVED** [review]
This look great! I'm not seeing any ads now!

Thank you, @fernandogelin!!!

**Pull request merged**
