### PR TITLE
File transfer services

### PR DESCRIPTION
**Pull request by AlexDuchnowski**
### Pull Request
---

#### PR Summary
Briefly describe the changes.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [x] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [x] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Review by yangliu2009 — APPROVED** [review]
Looks good. Thanks,

**Comment by paulstey** [comment]
Thanks for your work on this, @AlexDuchnowski!! Just to be clear, this currently links to a GitBook that's fairly empty—is that correct? Are we planning to add to that GitBook?

**Comment by AlexDuchnowski** [comment]
> Thanks for your work on this, @AlexDuchnowski!! Just to be clear, this currently links to a GitBook that's fairly empty—is that correct? Are we planning to add to that GitBook?

That is correct. I'm not sure if there is more content that will soon be added. @yangliu2009, do you have any extra information?

**Comment by yangliu2009** [comment]
@paulstey - You are right. The current linked GitBook is simple and has only one page which is for HEP users only. However, the GitBook does provide a space for more contents in the future. Thanks.

Yang

**Review by paulstey — APPROVED** [review]

**Pull request merged**
