### PR TITLE
Hibernate

### PR DESCRIPTION
**Pull request by singhsaluja**
### Pull Request
---

#### PR Summary
Briefly describe the changes.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [x] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ ] Commitizen was used for all commits.
- [ ] Local site looks as expected after changes.
- [ ] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Comment by paulstey** [comment]
Thanks for your work on this, @singhsaluja!! I only have two minor comments. First, I think it would be good to spell out what `NAS` is for a newer user. Also, the button says `Request Zone`, but we haven't specified what a Zone is yet, so it might be good to include a sentence that says what Zones are in Hibernate.

**Comment by mttunca** [comment]
Hi Paul - I had the same feedback regarding zones. Thanks a bunch!

Best,
Mete


-----------------------------------------
Mete Tunca
Associate Director, Research Systems and Services
Brown University | Center for Computation and Visualization
(401) 863-7293 (office)
(401) 793-0067 (mobile)
http://www.ccv.brown.edu

**Comment by singhsaluja** [comment]
Addressed both zones and NAS. @paulstey @mttunca, anything else needed?

**Review by paulstey — APPROVED** [review]
Thank you so much, @singhsaluja!! This is great!!!

**Review by yangliu2009 — APPROVED** [review]
Looks good to me. Thanks.

**Pull request merged**
