### PR TITLE
feat: 🎸 move rates table to shortcut and convert to HTML

### PR DESCRIPTION
**Pull request by fernandogelin**
### Pull Request
---

#### PR Summary
Update rates table, move to a shortcode as it's now HTML.
@singhsaluja  @yangliu2009 the table is now at:`ccv-website/themes/gb-theme/layouts/shortcodes/rates.html`

@singhsaluja @yangliu2009, can you take it from here and address changes if requested?

Please, review the content with attention as I just copied and pasted things.

Eventually we want to move the data out of the template, but for now, this should work.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [x] :dragon: Feature
- [x] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Comment by mcmcgrath13** [comment]
image

I find this confusing - if partition is a divider within row, it should probably be moved to the left or otherwise made more clear how to read an account row

**Review by mcmcgrath13 — CHANGES_REQUESTED** [review]
Technically, I approve. Content wise, I find the rows that are sub-partitioned by partition really hard to read.

**Review by singhsaluja — APPROVED** [review]

**Comment by singhsaluja** [comment]
@mcmcgrath13 You are right - we will make those changes in the future. We have to get this up asap so that users can apply for new accounts types.

**Comment by fernandogelin** [comment]
I think the new rates table and the new form are super confusing. For example, according to the table there are three types of Individual Exploratory, but the form only gives you one option. Same for Sponsored Exploratory.

**Pull request merged**
