### PR TITLE
prod - update facilities statement

### PR DESCRIPTION
**Pull request by paulstey**
This PR updates the `Facilities` statement, oscar specs, and new hiring.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [x] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ ] Commitizen was used for all commits.
- [ ] Local site looks as expected after changes.
- [ ] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Comment by mcmcgrath13** [comment]
I really think the oscar page also needs to be updated to match here - @AlexDuchnowski can you start a PR for that? We can sit on this merge until that is ready

**Review by mcmcgrath13 — CHANGES_REQUESTED** [review]
sync oscar page with this

**Comment by AlexDuchnowski** [comment]
> I really think the oscar page also needs to be updated to match here - @AlexDuchnowski can you start a PR for that? We can sit on this merge until that is ready

I am currently working on updating the Oscar specs in a separate branch for which I will submit a separate PR. Is this what you meant?

**Comment by mcmcgrath13** [comment]
> > I really think the oscar page also needs to be updated to match here - @AlexDuchnowski can you start a PR for that? We can sit on this merge until that is ready
> 
> I am currently working on updating the Oscar specs in a separate branch for which I will submit a separate PR. Is this what you meant?

Yup! Thanks!

**Review by mcmcgrath13 — APPROVED** [review]

**Pull request merged**
