### PR TITLE
feat: dedicated covid page

### LINKED ISSUE #230: [FEATURE] Add Covid-19 banner and updates section
Could we please create a small covid banner under the nav bar that links to a series of news and updates? The news and updates could also be linked from the front page in the _What's New_ section below the _Quick Links_.

I was thinking the covid banner could be something like `Covid-19 Resources & Updates`. 

And ideally, the linked section in _What's New_ could enable us to post updates in a logical manner (e.g., include a date, most recent at the top, _etc.).

What do you think, @mcmcgrath13 and @fernandogelin? As always, THANK YOU!!!

### PR DESCRIPTION
**Pull request by mcmcgrath13**
### Pull Request
---

#### PR Summary
Move covid updates to a dedicated page, trim down the banner, add to what's new

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [x] :blowfish: Other. Specify: moving things around

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [x] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

closes #230

### CODE REVIEW

**Comment by paulstey** [comment]
This looks great; thank you so much for your work on this, @mcmcgrath13!!! 

@fernandogelin and @mcmcgrath13: What would think about shrinking the covid banner just the bare minimum and placing it just below the nav bar? As it stands, the users may not see it without scrolling, depending on their screen and browser settings.

As a random side note, did the Heroku deployment not get triggered? I had to build this on my local machine.

**Comment by mcmcgrath13** [comment]
@paulstey @fernandogelin that would be fine with me - here's a preview:

image

**Review by paulstey — APPROVED** [review]
Thank you, Mary!! You're awesome!!

**Review by fernandogelin — APPROVED** [review]
I made some tweaks related to aligning things and changing styles. I also added the banner to the nav partial so it shows up in all pages, not only on the home page.

**Pull request merged**
