### PR TITLE
feat: 🎸 add Carney Condo details

### PR DESCRIPTION
**Pull request by yangliu2009**
add Carney Condo details

### Pull Request
---

#### PR Summary
Briefly describe the changes.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [x ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ x] Commitizen was used for all commits.
- [x ] Local site looks as expected after changes.
- [x ] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Review by paulstey — APPROVED** [review]
Thanks for your work on this, @yangliu2009!!! I hope you don't mind, but I made a change to make sure we capitalize "Carney".

Thanks again, Yang!!

**Comment by paulstey** [comment]
Hi @mttunca,

How are you? I am well! I have a question, please. When you have some time, could you take a look that this pull request? I think we just need your approval to merge.

Thank you, Mete!

Cheers,

Paul

**Review by mttunca — APPROVED** [review]

**Comment by mttunca** [comment]
Hi @paulstey - sorry about that, all set.

BTW, it brings me joy to hear you are well.

Best,
Mete

**Comment by paulstey** [comment]
Thank you, @mttunca!!

**Pull request merged**
