### PR TITLE
Feat status banner

### PR DESCRIPTION
**Pull request by fernandogelin**
### Pull Request
---

#### PR Summary
Add status banner.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [x] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [x] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Review by mirestrepo — APPROVED** [review]
Looks fantastic to me!

**Review by paulstey — APPROVED** [review]
This is awesome! Thank you, @fernandogelin!!!

**Review by mcmcgrath13 — COMMENTED** [review]
looks pretty good! my only concern from a technical perspective is this looks like it includes code from #289 which hasn't been approved/merged yet

**Comment by fernandogelin** [comment]
> looks pretty good! my only concern from a technical perspective is this looks like it includes code from #289 which hasn't been approved/merged yet

That's correct. but #289 should be merged before this one anyway because it's ready. The only issues are with the documents in KB that can be fixed by @mttunca's team, so I think #289 is ready.

**Pull request merged**
