### PR TITLE
fix: add matt slivinski to people section

### LINKED ISSUE #274: [DATA] Add Matt Slivinski to People section
**What would you like to update**
- [x] people
- [ ] opportunities

**If people, complete the object below. If adding new people, either add the images to this issue or send a slack message in `gh-ccv-website` after submitting this issue. **   

```
- name: 
  weight:  (order of card, first order by team, then by first name)
  type: 
  team: 
  subteam: 
  title: 
  github_username: 
  brown_directory_uuid: 
  bio: 
  image: <name>_main.jpg
```

**If opportunities:**  
```
- title: 
  team: 
  subteam: 
  link:
```
*link from jobs@brown site*

### PR DESCRIPTION
**Pull request by paulstey**
### Pull Request
Adding Matt to people section
closes #274 

#### PR Summary
This PR adds Matt Slivinski to the `People` section of our `About` page. The main and hover photo are also added.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [x] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Comment by paulstey** [comment]
This closes #274.

**Comment by fernandogelin** [comment]
The photo size looks odd, I can try to resize.

**Comment by fernandogelin** [comment]
also, if you want the PR to close the issue you need to specifically say: closes #274, otherwise the PR will just reference the issue.

**Comment by paulstey** [comment]
Thanks, @fernandogelin!!!

**Review by mcmcgrath13 — APPROVED** [review]

**Comment by fernandogelin** [comment]
@mcmcgrath13 can you review this again?

**Review by mcmcgrath13 — APPROVED** [review]

**Pull request merged**
