### PR TITLE
feat: 🎸 Updating Oscar Specs

### PR DESCRIPTION
**Pull request by AlexDuchnowski**
Updates infromation in table of Oscar details page

### Pull Request
---

#### PR Summary
Briefly describe the changes.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [x] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [x] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

### CODE REVIEW

**Comment by AlexDuchnowski** [comment]
@mcmcgrath13 Assuming the OS & Job Scheduler have not changed, the table should now be up to date (though the total storage number may need to be updated soon).

**Review by mcmcgrath13 — APPROVED** [review]

**Comment by paulstey** [comment]
Thanks, @AlexDuchnowski!! This looks great! 

One minor nit-pick: could we change the `300` to `400` on the Oscar card in the services page?

**Comment by AlexDuchnowski** [comment]
> Thanks, @AlexDuchnowski!! This looks great!
> 
> One minor nit-pick: could we change the `300` to `400` on the Oscar card in the services page?

@paulstey Of course! (I just pushed that change, so it should be good now.)

**Comment by paulstey** [comment]
Awesome!! Thank you, @AlexDuchnowski!!!

**Review by paulstey — APPROVED** [review]

**Pull request merged**
